### ISSUE TITLE
"Picture" vs. "Word" analysis code

### ISSUE THREAD

**Issue by joewiner** [psych-214-fall-2016/project-blue#12]
Design matrix will contrast "picture" trials and "word" trials for each subject (during encoding run). Above a set t-threshold, this contrast will be used as an ROI for next analyses

**Comment by joewiner** [comment]
@jdtheiss I think the model_signal script takes care of this issue - correct? You can go ahead and close this and the other issue if that's the case. But let us know what's missing, if not

**Comment by jdtheiss** [comment]
Yes, the model_signal module takes care of it.
