### ISSUE TITLE
Test for wrapper

### ISSUE THREAD

**Issue by joewiner** [psych-214-fall-2016/project-blue#17]

**Comment by joewiner** [comment]
@jdtheiss (and others) - do you think we should have a 'tests' folder within the code folder (like the glmtools assignment), or include a test function within each code script file?

@matthew-brett is there an advantage/disadvantage to doing either option?

**Comment by matthew-brett** [comment]
The typical arrangement is to have a "library" directory, that has your utility code, and a "scripts" directory, that has short scripts (of a few lines) that call the utility code.

For your projects, my implicit suggestion is that you have this stucture, in your `code` directory:

* `fmri_utils` - library code
* `fmri_utils/tests` - tests for library code
* `scripts`  - scripts that call library code

I suggest that you put all the tests into `test_*.py` functions in `fmri_utils/tests` - even the tests for the scripts.  It's no big deal either way, but the advantage is that it's easier to see at a glance where the tests are, and what the structure of the code is (no testing clutter in the code directory).

**Comment by joewiner** [comment]
Thanks. My next commit will follow this structure

**Comment by joewiner** [comment]
As of 12/6, the wrapper needs tests and motion correction script has a few lines that are not tested

**Comment by jdtheiss** [comment]
@joewiner where can I find that so I can update the tests for motion correction?

**Comment by joewiner** [comment]
@jdtheiss if you scroll to the bottom of https://codecov.io/gh/psych-214-fall-2016/project-blue you can see specific files / lines that aren't tested with the current tests. It looks like it isn't testing the case where the reference shape == 4.

**Comment by jdtheiss** [comment]
@joewiner Ok cool, thanks. I'll fix that.

**Comment by mlnewton** [comment]
Not sure how to make tests for wrapper; Input appreciated.

**Comment by joewiner** [comment]
Changed issue title to reflect ongoing need for wrapper test - @mlnewton if you are going to be finishing the wrapper, maybe @qaydm1979 could write the test? We can also work this out when we meet tomorrow.
