### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mlnewton** [psych-214-fall-2016/project-blue#28]
I will be updating README.md and emulating format of previous class's projects posted on PSYCH214 (such as this https://github.com/berkeley-stat159/project-alpha/blob/master/README.md). This will make wrapper.py clear to run.

**Comment by joewiner** [comment]
@mlnewton if you want to take a look at current README pull request and make any edits, i think we should be good on this issue

**Comment by jdtheiss** [comment]
I think the updated README looks good, but we can make some last-minute changes if anyone needs to.
