### ISSUE TITLE
Fix slice timing correction

### ISSUE THREAD

**Issue by joewiner** [psych-214-fall-2016/project-blue#32]
I will fix slice timing code based on the comments received 12/5

**Comment by joewiner** [comment]
So the file 'task-visualimageryfalsememory_bold.json' includes slice timing info for the study - I was thinking it might be good to use that information. Is it possible to import it from the json file?

**Comment by jdtheiss** [comment]
Hell yeah it is. Just use my function "get_contents" from the dir_utils module: 

outputs = get_contents('task-visualimageryfalsememory_bold.json', ['SliceTiming'])
slice_timing = outputs[0]

**Comment by joewiner** [comment]
Excellent! Will do. Thanks!

**Comment by mlnewton** [comment]
suggestion for how we can make test for slice timing: https://matthew-brett.github.io/teaching/slice_timing.html --> bottom

**Comment by mlnewton** [comment]
https://github.com/practical-neuroimaging/pna-utils/blob/master/slicetime.py
Was the method you think is best at our last meeting? I want to try to figure out what "padding" is for the first time point (I still think we should just use the first timepoint as is, without any interpolation or fancy changes).

**Comment by joewiner** [comment]
Yes - I would look at our conversation on the slice timing pull request. If you read about padding and have a suggestion let me know! I should have time to get to the slice timing code later today
