### ISSUE TITLE
Filter for scanner drift

### ISSUE THREAD

**Issue by joewiner** [psych-214-fall-2016/project-blue#42]
I found this - http://nipy.org/nitime/examples/filtering_fmri.html
Looks like it may have been written by Matthew, haha. I should be able to implement it into the preprocessing. Do you guys think it should come after outlier detection?

**Comment by mlnewton** [comment]
Was the method you think is best at our last meeting? I want to try to figure out what "padding" is for the first time point (I still think we should just use the first timepoint as is, without any interpolation or fancy changes).

**Comment by jdtheiss** [comment]
Based on our discussion at the meeting yesterday, I think we've agreed that we'll implement a polynomial regressor in the design matrix. This will be added to the model_signal module.
