### ISSUE TITLE
Evaluate questionaire data for correlation with BOLD

### ISSUE THREAD

**Issue by mlnewton** [psych-214-fall-2016/project-blue#45]
Looking into this now

**Comment by mlnewton** [comment]
from Openfmri 'participants.json', description of the tests. These 3 seem to be the main measures. Still can't find the actual scores for each subject, though...

"LSHS_14, "Launay-Slade Hallucination Scale"
        "Description": "Proneness to hallucinations in healthy participants"

    "DELUproneness, "Proneness to delusions",
        "Description": "Proneness to delusions was assessed by means of the Peters Delusion Inventory scale"
    
 "VisualScore": "Visual imagery score",
        "Description": "The subjects were asked to self-rate the truth of the following statements using a 0-3 scale, 0 being the least true: 'I can easily identify animals or things in the clouds', 'When I see spots (of painting, humidity...), I can see faces, silhouettes or objects in them.' The sum of these two scores constitutes the VisualScore",
        "Units": "0-6, 0 being lowest proneness to visual imagery"

**Comment by joewiner** [comment]
Scores are in the participants.tsv file

**Comment by mlnewton** [comment]
Just got it, thanks. Had to re-download the file since it must have accidentally gotten deleted or moved

**Comment by mlnewton** [comment]
So they really only used divisions and variants of 2 accepted evaluations: the Launay-Slade Hallucination Scale (LSHS) and the Peters Delusion Inventory (PDI) scale.

Here's an interesting discussion about how the LSHS does not necessarily capture the same experiences in non-clinical and clinical populations despite answering the same way to the survey questions: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3363387/
An excerpt: 'On RHS item 1 (“My thoughts seem as real as actual events in my life”), the non-clinical sample described experiences classifiable as magical thinking (e.g., “Sometimes I imagine situations that I want to happen to me and they happen”), whereas the clinical sample described experiences reflecting dereistic thinking (e.g., “I believe that my brother was dead when he was really alive”)'

And here's what appears to be a photocopied version of a chapter on the PDI that also reviews other testing scales:
http://schizophreniabulletin.oxfordjournals.org/content/30/4/1005.long

**Comment by joewiner** [comment]
So if you look at what's written on LSHS and PDI, and also look at the
range of scores in this group of subjects, do you think one would be better
to look at than the other? It seems like LSHS has a pretty good range. We
could try exploring both, as well as the subscores they list in the .tsv
file

**Comment by mlnewton** [comment]
I think we should look at both the LSHS global scores ('LSHS_14') and the PDI scores ('DELUproneness'), but the LSHS scores are more relevant to sensory encoding/retrieval while the PDI is more internal, thought-driven. Both would be interesting to consider for correlation with incorrectly recalling a visual stimulus.

**Comment by mlnewton** [comment]
I don't think we should use any of the other measurements because they are not validated elsewhere and do not have enough power to make any conclusions with so few total questions.

**Comment by jdtheiss** [comment]
Thanks for looking into the different scales, Melissa. I agree we should just use the LSHS and PDI scores. This will be implemented in the wrapper.

**Comment by joewiner** [comment]
@mlnewton do you feel comfortable closing this issue? Seems like you've done a thorough evaluation!

**Comment by mlnewton** [comment]
Yep, sounds good to close
